sonar.projectKey=cashflow
sonar.projectName=Cashflow
sonar.sourceEncoding=UTF-8

sonar.sources=lib,scripts
sonar.tests=test,integration_test
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,build/**,coverage/**,**/.dart_tool/**,android/**,ios/**,macos/**,linux/**,windows/**,web/**
sonar.test.inclusions=test/**/*.dart,integration_test/**/*.dart
sonar.dart.coverage.reportPaths=coverage/lcov.info